### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lishine** [danielrearden/sqlmancer#14]
Hi Daniel,

Link with this text before it is broken:
Read more about defining models.

Questions:
What is the background for creating this lib and even with support for many databases? You are using it at your work?
There is prisma, how is it compares, why create something similar?

**Comment by lishine** [comment]
Is it possible to do nested creates and updates?

**Comment by danielrearden** [comment]
Hi Pavel. Thanks for pointing that out!

The docs will get a complete overhaul once I've wrapped up all the features I have slated for a beta release. I'm hoping to add a FAQ section that will help outline the differences between this and similar tools. In the meantime, to answer your questions:

* Sqlmancer is not currently being used in production, but was created with the intent to utilize it as part of several projects I am currently a part of. While there are a number of great tools out there already (Hasura, PostGraphile, Prisma, etc.), none of them offered all the features I was looking for in a solution.
* This project is indeed similar to Prisma, at least in that it generates a database client for you to use. The main differences are:
  * Prisma abandoned schema binding, meaning there's no way to write a SDL schema, use their client inside your resolvers and have it infer the SQL from the request. The only way to bind your schema to your models like that now is to use Nexus to create your schema, which is a code-first library. Sqlmancer, on the other hand, is able to parse the `GraphQLResolveInfo` object passed to the resolver to determine what data needs to be fetched. This makes writing resolvers even for arbitrarily complex queries super simple.
  * On top of the schema binding described above, which was possible in Prisma 1, Sqlmancer also lets you modify the options set by parsing the `GraphQLResolveInfo` object. So you can add additional qualifiers to your query based on, for example, the context. So instead of just having a `posts` field, you can have a `myPosts` field that returns only the logged-in user's posts, all with minimal effort.
  * Sqlmancer supports long-running transactions. You can initialize a transaction and perform any number of read or write queries inside it. Prisma doesn't support this feature, which is *why* it has nested creates and updates -- it's the only way to utilize transactions with Prisma. With Sqlmancer, this becomes unnecessary -- you can already utilize a single transaction to perform whatever operations you want your resolver to do.
  * Sqlmancer provides significantly more robust querying, filtering and aggregation capabilities than Prisma. You can, for example, filter and sort by related model properties and aggregated values of those properties. Prisma only supports `count` aggregation while Sqlmancer will include other common aggregate functions by the time it hits beta.
  * Sqlmancer lets you define "virtual fields" that depend on one or more columns.
  * Sqlmancer includes support for abstract types like unions and interfaces. 
  * Sqlmancer includes support for using views instead of tables. By the time it hits beta, it will also support creating explicitly "read-only" models that either utilize views defined in your database or utilize CTEs for generating views on the fly.
  * Sqlmancer uses decorators to describe your data models inside your type definitions, while Prisma requires a separate model definitions file.
  * Prisma is a database client first, with some GraphQL integration through Nexus. Sqlmancer is a tool to "teach" your GraphQL service how to integrate with your database. Sqlmancer could accomplish this without generating a database client (all the information it needs is in your type definitions after all), but it does so to empower you to decouple your business logic from your resolvers.

A lot of the differences outlined above also apply to other existing tools. And while Hasura and PostGraphile actually include *most* of the features missing from Prisma, their usage is limited to Postgres only. I wanted to create a free, open-source library that supported a wide variety of SQL dialects so that it could be used with existing applications as well as new ones.

If you have any other questions or feedback, please let me know :)

**Comment by lishine** [comment]
Thank you! It is very cool! I hope it will be success. This ecosystem need these end to end integration. 
I will ask hard questions 😉 . It is like these HR questions - to tell in what you are bad.
1. I understand. Indeed prisma currently is code first only through nexus. And you listed it's missing features. But what are it's advantages? In what they so much invest with a big team and at the same time missing these features.
2. Prisma can infer schema from db and has the experimental migrations. So eventually will be single source of truth - code first scheme. Hasura also does migrations and the scheme is built on the db through it's interface. 
In this case migrations are taken care outside of the lib or with knex. And actually there are two source of truth - the Graphql model with db models and db scheme itself.

**Comment by danielrearden** [comment]
The main advantage I see to Prisma's approach is that it [abstracts away the complexity of working with SQL](https://www.prisma.io/docs/understand-prisma/why-prisma#application-developers-should-care-about-data--not-sql). And while I understand that point of view, that additional level of abstraction makes it more difficult to handle more complex use cases. It's like using an ORM versus writing raw SQL. An ORM makes things simpler and enables you to write application code without a deep understanding of SQL. But we often find that the ORM we're using either doesn't support something we could easily do with raw SQL or else requires some additional workaround to make it work. Neither approach is inherently *bad* and you have to choose what's right for your application.

You're absolutely right that existing solutions enable you to have a "single source of truth". And it's certainly possible to eventually add a CLI utility that would let you do migrations based on the generated Sqlmancer models -- I think something like that would be great DX for scaffolding projects or putting together a POC.

However, I think *because* there's a single source of truth, the existing solutions also encourage a one-to-one mapping between your database tables and your GraphQL types. On the other hand, with Sqlmancer's approach, we can have a set of tables that persist the data in an optimized way while potentially utilizing views  (inline or otherwise) to generate data that's the right shape for the clients querying the GraphQL service. In this sense, Sqlmancer allows your GraphQL schema to be at least somewhat decoupled from the underlying database schema.

**Comment by danielrearden** [comment]
Closing this since the question has been answered. Should add some of the above discussion to the docs when a FAQ section is added, though.
