### ISSUE TITLE
Question - athorization

### ISSUE THREAD

**Issue by lishine** [danielrearden/sqlmancer#47]
What would be the recommended approach to limit orders (order has customerId field) query only to users that are associated with these customers in a connected table customerUsers(userId, customerId) ?
resolver of orders
```
        async orders(_, __, { client, userId }, info) {
            return client.models.Order.paginate().count().selectAll().resolveInfo(info).execute()
        },
```
userId comes from the context
1. Inner join  (using knex??, is it possible at all to use knex with sqlmancer client?) with customerUsers(where userId = contextUserId)
2. Somehow complement the request to be
```
query {
   orders {
      users(where: { userId: contextUserId})
   }
}
```
3. Something like graphql-shield (I don't know yet if it is feasible)
4. Permissions on postgres itself (have to investigate, I don't know yet anything about it)

**Comment by lishine** [comment]
5. approach
In the orders resolver, make another use of the client to find all customers related to current userId.
Then add these customerIds to the where
I think this is what I will implement right now

**Comment by danielrearden** [comment]
```
async orders(_, __, { client, userId }, info) {
  return client.models.Order.paginate()
    .resolveInfo(info)
    .mergeWhere({ userId })
    .execute()
},
```

`resolveInfo` will call the `where` method for you based on the query. If you call `where` again, it will override whatever is set by `resolveInfo`. If you call `mergeWhere`, it will merge in the provided criteria instead. I mentioned this in the docs [here](https://sqlmancer.netlify.app/filtering#adding-on-to-a-query-builder) but let me know if you think it could be clearer.

GraphQL shield would be a good fit if you just wanted to throw an error when accessing a field that a user is not authorized to access period (maybe because they're not logged in).

If you wanted to utilize [row-level security](https://www.postgresql.org/docs/9.5/ddl-rowsecurity.html) like PostGraphile does, this should be possible too. Provided you've configured your tables correctly, you'd just need to do something like:

```
return client.transaction(trx => {
  await client.raw(`SET ROLE ?`, [USER_ROLE_FROM_CONTEXT])
  return client.models.Order.paginate().resolveInfo(info).execute()
})
```

**Comment by lishine** [comment]
You say that GraphQL shield is more to throw an error . It can't be used to return only these orders that their customerId is associated with current userId.
I have to yet learn how to do  row-level security like PostGraphile .
But I used permissions in Hasura. There you set rules through the interface, it does automatically the joins and only the relevant data is returned.
With sqlmancer you say that I have to add some sql in each resolver (it is actually I am just passing the auth parameters to the db)?
So it is not enough some one-time setup like in Hasura so it later on acts automatically without adding stuff to resolvers (what if I forget to add?) ?

**Comment by danielrearden** [comment]
Implementing any kind of methods related to authorization is, I think, out of scope for this library. I'm open to changes that can make implementing certain authorization mechanisms easier (like #12).

To avoid having to inject the role inside every resolver, we'd need a way to set the role just once for an entire client instance (for example, inside the context function). Maybe we could provide generic `append` and `prepend` methods on the client instance themselves. Then, if set, those statements could be automatically ran before/after every call to the database.

**Comment by lishine** [comment]
Great

**Comment by danielrearden** [comment]
Closing this issue since the question was answered. We can flesh out authorization recipes once the API is stable.
